print("i will count my chickens")
print("hens",25+30/6)
print("roosters",100-25*3%4)
print("now i will count the eggs:")
print(3+2+1-5+4%2-1/4+6)
print("is it true that 3+2<5-7?")
print(3+2<5-7)
print("what is 3+2?",3+2)
print("oh, that is why it is false.")
print("what is my name",2+3)
print("what is my name",'nandan')
print("is it greater?",5 > -2)
print("is ti greater or equal?", 5 >= -2)
